### ISSUE TITLE
unable to run webpack reload

### ISSUE THREAD

**Issue by mosesliao** [GrandFelix/cakephp-webpack#1]
I keep getting this error for my cakephp setup

```
Exception: Folder does not exists! in [/var/www/html/vendor/grandfelix/cakephp-webpack/src/Shell/Task/ReloadTask.php, line 185]
2018-05-19 23:44:40 Error: [Exception] Folder does not exists! in /var/www/html/vendor/grandfelix/cakephp-webpack/src/Shell/Task/ReloadTask.php on line 185
Stack Trace:
#0 /var/www/html/vendor/grandfelix/cakephp-webpack/src/Shell/Task/ReloadTask.php(44): GrandFelix\Webpack\Shell\Task\ReloadTask->getAliasPath('', Array)
#1 /var/www/html/vendor/cakephp/cakephp/src/Console/Shell.php(507): GrandFelix\Webpack\Shell\Task\ReloadTask->main()
#2 /var/www/html/vendor/cakephp/cakephp/src/Console/Shell.php(500): Cake\Console\Shell->runCommand(Array, false, Array)
#3 /var/www/html/vendor/cakephp/cakephp/src/Console/CommandRunner.php(141): Cake\Console\Shell->runCommand(Array, true)
#4 /var/www/html/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#5 {main}
```

what do I miss out?

**Comment by GrandFelix** [comment]
Hi @liaogz82,

I think one of your config's is misconfigured. One of configured paths to resources does not exists. Are you sure that all configured paths exists?

**Comment by GrandFelix** [comment]
@liaogz82 I assume that this issue is resolved as there was no answer for 2 weeks. So Im closing it. If you have any more troubles pleas fill new issue.
